# Generated by Django 5.1.2 on 2024-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
