# Generated by Django 5.1.2 on 2024-10-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.OneToOneField(default='100', on_delete=django.db.models.deletion.CASCADE, to='timetable_generator.login'),
        ),
    ]
