# Generated by Django 5.1.2 on 2024-11-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0004_department_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestername', models.CharField(max_length=40)),
            ],
        ),
    ]
