# Generated by Django 5.1.2 on 2024-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0005_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Faculty', 'Faculty'), ('Hod', 'Hod')], max_length=40),
        ),
    ]
